import { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

const API = import.meta.env.VITE_API_URL || 'http://127.0.0.1:5000'
const sections = {
  overview: { label: 'Overview', views: [['dashboard', 'Dashboard'], ['health', 'Health snapshot']] },
  segments: { label: 'Segments', views: [['rfm', 'RFM segments'], ['value', 'Value tiers']] },
  retention: { label: 'Retention', views: [['risk', 'Risk queue'], ['drivers', 'Model drivers']] },
  customers: { label: 'Customer 360', views: [['directory', 'Directory'], ['profiles', 'Profiles']] },
  revenue: { label: 'Revenue', views: [['performance', 'Performance'], ['products', 'Products & markets']] },
  actions: { label: 'Actions', views: [['playbook', 'Action playbook'], ['queue', 'Priority queue']] },
  method: { label: 'Method', views: [['pipeline', 'Pipeline'], ['sql', 'SQL & performance']] },
}
const validPage = page => Object.hasOwn(sections, page) ? page : 'overview'
const money = n => n >= 1e6 ? `£${(n / 1e6).toFixed(2)}M` : `£${Math.round(n || 0).toLocaleString()}`
const percent = n => `${((n || 0) * 100).toFixed(1)}%`

function BarChart({ title, data = [], valueKey = 'revenue', labelKey = 'rfm_segment', format }) {
  const max = Math.max(1, ...data.map(x => x[valueKey] || 0)); const show = format || (valueKey.includes('revenue') ? money : n => Number(n || 0).toLocaleString())
  return <section className="panel chart"><div className="panel-head"><h3>{title}</h3><span>Live data</span></div><div className="bars">{data.slice(0, 10).map((row, i) => <div className="bar-row" key={`${row[labelKey]}-${i}`}><div className="bar-label">{row[labelKey]}</div><div className="bar-track"><i style={{ width: `${((row[valueKey] || 0) / max) * 100}%` }}/></div><strong>{show(row[valueKey])}</strong></div>)}</div></section>
}

function Table({ title, rows = [], columns, onRowClick }) {
  return <section className="panel table"><div className="panel-head"><h3>{title}</h3><span>{rows.length} records</span></div><div className="data-table"><div className="tr th">{columns.map(c => <span key={c.key}>{c.label}</span>)}</div>{rows.map((row, i) => <button className="tr" onClick={() => onRowClick?.(row)} key={`${row.customer_id || i}`}>{columns.map(c => <span key={c.key}>{c.render ? c.render(row[c.key], row) : row[c.key]}</span>)}</button>)}</div></section>
}

function Metrics({ metrics = [] }) { return <section className="metric-grid">{metrics.map(m => <article className="metric" key={m.label}><span>{m.label}</span><strong>{m.value}</strong><small>{m.detail}</small></article>)}</section> }
function Insights({ items = [] }) { return <section className="insights">{items.map((item, i) => <article key={item}><b>0{i + 1}</b><p>{item}</p></article>)}</section> }

function Hero({ page, navigate }) {
  const compact = page !== 'overview'
  return <section className={`hero ${compact ? 'compact' : ''}`}><video autoPlay loop muted playsInline><source src="https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260403_050628_c4e32401-fab4-4a27-b7a8-6e9291cd5959.mp4"/></video><div className="hero-shade"/>
    <header><button className="brand" onClick={() => navigate('overview')}>SALESLENS</button><nav>{Object.entries(sections).map(([id, section]) => <button className={page === id ? 'active' : ''} key={id} onClick={() => navigate(id)}>{section.label}</button>)}</nav><button className="nav-cta" onClick={() => navigate('actions', 'queue')}>View actions</button></header>
    {compact ? <div className="compact-copy"><p className="eyebrow">Customer intelligence / {sections[page].label}</p><h1>{sections[page].label}</h1></div> : <div className="hero-content"><p className="eyebrow">Customer 360 · Revenue intelligence</p><h1>Turn customer signals<br/>into decisive action.</h1><p className="hero-copy">An analyst workspace for identifying customer value, preventing churn, and prioritising the next revenue action.</p><div className="hero-buttons"><button onClick={() => navigate('overview')}>Explore intelligence</button><button className="ghost" onClick={() => navigate('actions', 'playbook')}>View action plan</button></div></div>}
  </section>
}

function Subnav({ page, view, navigate }) { return <div className="subnav"><span>Explore {sections[page].label}</span>{sections[page].views.map(([id, label]) => <button key={id} className={view === id ? 'active' : ''} onClick={() => navigate(page, id)}>{label}</button>)}</div> }

function CohortControls({ filters, values, setValues }) {
  const [open, setOpen] = useState(false); const items = [['health', 'Health'], ['rfm', 'RFM segment'], ['risk', 'Churn risk'], ['action', 'Action priority'], ['value', 'Value tier'], ['country', 'Country']]
  return <section className="controls"><button onClick={() => setOpen(!open)}>Cohort controls {Object.values(values).filter(Boolean).length ? '• active' : ''}</button>{open && <div className="control-popover">{items.map(([key, label]) => <label key={key}>{label}<select value={values[key] || ''} onChange={e => setValues({...values, [key]: e.target.value})}><option value="">All {label.toLowerCase()}s</option>{(filters[key] || []).map(v => <option key={v}>{v}</option>)}</select></label>)}<label>Minimum revenue<input type="number" min="0" value={values.revenue_min || ''} onChange={e => setValues({...values, revenue_min: e.target.value})} placeholder="e.g. 1000"/></label><label>Minimum churn probability<input type="number" min="0" max="1" step=".05" value={values.probability_min || ''} onChange={e => setValues({...values, probability_min: e.target.value})} placeholder="0.00–1.00"/></label><button className="clear" onClick={() => setValues({})}>Clear filters</button></div>}</section>
}

function CustomerDirectory({ view, queryString }) {
  const [search, setSearch] = useState(''), [query, setQuery] = useState(''), [page, setPage] = useState(1), [result, setResult] = useState({ records: [], pages: 1, total: 0 }), [selected, setSelected] = useState(null)
  useEffect(() => { setPage(1) }, [queryString])
  useEffect(() => { fetch(`${API}/api/customers?search=${encodeURIComponent(query)}&page=${page}&limit=12&${queryString}`).then(r => r.json()).then(setResult) }, [query, page, queryString])
  const choose = c => fetch(`${API}/api/customer/${c.customer_id}`).then(r => r.json()).then(setSelected)
  const cols = [{key:'customer_id',label:'Customer',render:v => `#${v}`},{key:'country_mode',label:'Country'},{key:'rfm_segment',label:'Segment'},{key:'churn_risk_tier',label:'Churn risk'},{key:'total_revenue',label:'Revenue',render:money}]
  return <><section className="panel directory"><div className="panel-head directory-head"><div><h3>{view === 'profiles' ? 'Customer profile browser' : 'Customer directory'}</h3><span>{result.total.toLocaleString()} matching customers</span></div><form onSubmit={e => { e.preventDefault(); setPage(1); setQuery(search) }}><input value={search} onChange={e => setSearch(e.target.value)} placeholder="ID, country or segment"/><button>Search</button></form></div><Table title="" rows={result.records} columns={cols} onRowClick={choose}/><div className="pagination"><button disabled={page === 1} onClick={() => setPage(page - 1)}>← Previous</button><span>Page {page} of {result.pages}</span><button disabled={page === result.pages} onClick={() => setPage(page + 1)}>Next →</button></div></section>{selected && <section className="profile"><div><p className="eyebrow dark">Customer profile</p><h3>#{selected.customer_id} · {selected.country_mode}</h3><p>{selected.final_recommended_action}</p></div><div className="profile-metrics"><span><b>{money(selected.total_revenue)}</b>Revenue</span><span><b>{percent(selected.churn_probability)}</b>Churn probability</span><span><b>{selected.customer_health_score?.toFixed(0)}</b>Health score</span><span><b>{selected.total_invoices}</b>Invoices</span></div></section>}</>
}

function Method({ view }) { return <section className="method"><p className="eyebrow dark">{view === 'sql' ? 'SQL & scale' : 'Reproducible workflow'}</p>{view === 'sql' ? <><h3>Analytical SQL designed for data at scale.</h3><div className="method-grid"><article><b>01</b><h4>Columnar storage</h4><p>Parquet enables selective reads and lower I/O for analytical workloads.</p></article><article><b>02</b><h4>Query design</h4><p>Filter early, pre-aggregate at customer grain, and inspect query plans before scaling.</p></article><article><b>03</b><h4>Warehouse-ready</h4><p>The model maps directly to Redshift, Databricks, or StarRocks partitioned tables.</p></article></div></> : <><h3>From raw retail data to an accountable customer action.</h3><ol><li>Audit and clean 779k transaction records; reconcile revenue.</li><li>Build RFM, engagement, return, and revenue features.</li><li>Score churn risk, customer health, and customer value.</li><li>Give every customer a recommended retention or growth action.</li></ol></>}</section> }

function PageContent({ page, view, dashboard, pageData, queryString }) {
  if (!dashboard || (page !== 'overview' && !pageData)) return <div className="loading">Loading live analytics…</div>
  if (page === 'customers') return <CustomerDirectory view={view} queryString={queryString}/>
  if (page === 'method') return <Method view={view}/>
  if (page === 'overview') return view === 'health' ? <><Metrics metrics={dashboard.metrics}/><section className="two-col"><BarChart title="Revenue by health tier" data={dashboard.health} labelKey="health_tier"/><BarChart title="Customers by churn risk" data={dashboard.risk} valueKey="customers" labelKey="churn_risk_tier"/></section><Insights items={dashboard.insights}/></> : <><Metrics metrics={dashboard.metrics}/><section className="two-col"><BarChart title="Revenue by customer segment" data={dashboard.segments}/><BarChart title="Customers by action priority" data={dashboard.priorities} valueKey="customers" labelKey="action_priority"/></section><Insights items={dashboard.insights}/></>
  if (page === 'segments') return <><section className="two-col"><BarChart title={view === 'value' ? 'Revenue by value tier' : 'RFM segment revenue'} data={view === 'value' ? pageData.value : pageData.rfm} labelKey={view === 'value' ? 'customer_value_tier' : 'rfm_segment'}/><BarChart title="Customer volume" data={view === 'value' ? pageData.value : pageData.rfm} valueKey="customers" labelKey={view === 'value' ? 'customer_value_tier' : 'rfm_segment'}/></section><Table title="Segment performance" rows={pageData.table} columns={[{key:'rfm_segment',label:'Segment'},{key:'customers',label:'Customers'},{key:'revenue',label:'Revenue',render:money},{key:'avg_recency_days',label:'Avg. recency',render:v => `${v.toFixed(0)} days`},{key:'avg_churn_probability',label:'Churn',render:percent}]}/></>
  if (page === 'retention') return view === 'drivers' ? <><Table title="Churn-model drivers" rows={pageData.drivers} columns={[{key:'feature',label:'Feature'},{key:'direction',label:'Impact'},{key:'coefficient',label:'Coefficient',render:v => Number(v).toFixed(3)},{key:'abs_coefficient',label:'Magnitude',render:v => Number(v).toFixed(3)}]}/><Table title="Validation metrics" rows={pageData.model_metrics} columns={[{key:'model',label:'Model'},{key:'accuracy',label:'Accuracy',render:percent},{key:'recall',label:'Recall',render:percent},{key:'roc_auc',label:'ROC-AUC',render:percent}]}/></> : <><section className="two-col"><BarChart title="Revenue at risk by tier" data={pageData.risk} labelKey="churn_risk_tier"/><BarChart title="Customers by churn probability" data={pageData.distribution} valueKey="customers" labelKey="probability_band"/></section><Table title="Highest-risk customer queue" rows={pageData.high_risk} columns={[{key:'customer_id',label:'Customer',render:v=>`#${v}`},{key:'country_mode',label:'Country'},{key:'churn_risk_tier',label:'Risk'},{key:'churn_probability',label:'Probability',render:percent},{key:'total_revenue',label:'Revenue',render:money},{key:'final_recommended_action',label:'Recommended action'}]}/></>
  if (page === 'revenue') return view === 'products' ? <><section className="two-col"><BarChart title="Top markets by revenue" data={pageData.countries} labelKey="country"/><BarChart title="Top products by revenue" data={pageData.products} labelKey="description"/></section><Table title="Product performance" rows={pageData.products} columns={[{key:'stock_code',label:'SKU'},{key:'description',label:'Product'},{key:'revenue',label:'Revenue',render:money},{key:'quantity',label:'Units',render:v=>Number(v).toLocaleString()},{key:'customers',label:'Customers'}]}/></> : <><BarChart title="Monthly revenue" data={pageData.monthly} labelKey="invoice_yearmonth"/><Table title="Monthly performance" rows={pageData.monthly} columns={[{key:'invoice_yearmonth',label:'Month'},{key:'revenue',label:'Revenue',render:money},{key:'invoices',label:'Invoices'},{key:'customers',label:'Active customers'},{key:'average_order_value',label:'AOV',render:money}]}/></>
  return view === 'queue' ? <Table title="Prioritised action queue" rows={pageData.queue} columns={[{key:'customer_id',label:'Customer',render:v=>`#${v}`},{key:'action_priority',label:'Priority'},{key:'final_recommended_action',label:'Recommended action'},{key:'churn_probability',label:'Churn',render:percent},{key:'total_revenue',label:'Revenue',render:money},{key:'health_tier',label:'Health'}]}/> : <><section className="two-col"><BarChart title="Revenue represented by priority" data={pageData.priorities} labelKey="action_priority"/><BarChart title="Customer health mix" data={pageData.health} valueKey="customers" labelKey="health_tier"/></section><Table title="Action playbook" rows={pageData.plan} columns={[{key:'action_priority',label:'Priority'},{key:'final_recommended_action',label:'Recommended action'},{key:'customers',label:'Customers'},{key:'revenue',label:'Revenue',render:money},{key:'average_churn_probability',label:'Churn',render:percent}]}/><div className="downloads"><a href={`${API}/api/export/customers?${queryString}`}>Download customers</a><a href={`${API}/api/export/high-risk?${queryString}`}>Download high risk</a><a href={`${API}/api/export/vip?${queryString}`}>Download VIPs</a><a href={`${API}/api/export/action-plan?${queryString}`}>Download action plan</a></div></>
}

function App() {
  const readRoute = () => { const params = new URLSearchParams(location.search), page = validPage(params.get('page') || 'overview'), candidate = params.get('view'); return {page, view: sections[page].views.some(v => v[0] === candidate) ? candidate : sections[page].views[0][0]} }
  const [route, setRoute] = useState(readRoute()), [dashboard, setDashboard] = useState(null), [pageData, setPageData] = useState(null), [filters, setFilters] = useState({}), [values, setValues] = useState({})
  const queryString = useMemo(() => new URLSearchParams(Object.entries(values).filter(([,v]) => v)).toString(), [values])
  const navigate = (page, view = sections[page].views[0][0]) => { history.pushState({}, '', `?page=${page}&view=${view}`); setRoute({page, view}); window.scrollTo({top:0, behavior:'smooth'}) }
  useEffect(() => { fetch(`${API}/api/filters`).then(r=>r.json()).then(setFilters) }, [])
  useEffect(() => { const handler = () => setRoute(readRoute()); addEventListener('popstate', handler); return () => removeEventListener('popstate', handler) }, [])
  useEffect(() => { setDashboard(null); fetch(`${API}/api/dashboard?${queryString}`).then(r=>r.json()).then(setDashboard) }, [queryString])
  useEffect(() => { if (route.page === 'overview' || route.page === 'method' || route.page === 'customers') { setPageData(null); return }; setPageData(null); fetch(`${API}/api/${route.page}?${queryString}`).then(r=>r.json()).then(setPageData) }, [route.page, queryString])
  return <><Hero page={route.page} navigate={navigate}/><main><div className="section-top"><div><p className="eyebrow dark">Live analyst workbench</p><h2>{sections[route.page].label}<span> · Customer intelligence</span></h2></div><CohortControls filters={filters} values={values} setValues={setValues}/></div><Subnav {...route} navigate={navigate}/><PageContent {...route} dashboard={dashboard} pageData={pageData} queryString={queryString}/></main><footer>SalesLens · prepared by Abhinav Kumar · AI-Native Data Analyst Intern Candidate</footer></>
}
createRoot(document.getElementById('root')).render(<App />)

